name: document_analysis
description: A collection of document-analysis processing. Includes tokenization, distance, similarity, etc.
version: 0.1.2
author: Vincent Utomo <msvcode@gmail.com>
homepage: https://github.com/MSVCode/document-analysis-dart
repository: https://github.com/MSVCode/document-analysis-dart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

dev_dependencies:
